name: README code output

on: [push]

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.GH_ACTIONS_PAT }}


      # Runs a set of commands using the runners shell
      - name: Update README.md
        run: |
          # cd StanfordAlgorithms
          # sh scripts/setup.sh
          sh scripts/update_all_readmes.sh
          # git config user.name Bruno Mariz
          # git config user.email bmarizot@gmail.com
          git add .
          git commit -m "generated"
          git push
