name: README code output

on: [push]

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      # Runs a set of commands using the runners shell
      - name: Update README.md
        run: |
          cd StanfordAlgorithms
          sh actions/update_all_readmes.sh
          # git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # git config user.name "github-actions[bot]"
          # git commit -am "Automated report"
          # git push

      - name: Commit Readme
        uses: EndBug/add-and-commit@v9
